### ISSUE TITLE
Will you be uploading this to the vencord plugin (list/hub)?

### ISSUE THREAD

**Issue by TheRealFame** [nyakowint/vc-premid#3]
I'm curious! I wanna try this with premid on linux, And i don't know how to compile vencord.

**Comment by nyakowint** [comment]
Huh. Is this still needed on linux? Because Premid's newest extension update does this themselves through a discord gateway capability

Probably not though. The annoyances I had to go through to even make this a userplugin is not worth trying to refactor into an approvable first party plugin + it wouldn't get merged anyways

considering you're on linux you should be familiar with the command line to a certain extent - so building vencord is very simple

See https://github.com/Vendicated/Vencord/blob/main/docs/1_INSTALLING.md

>[!NOTE]
 Installs of this kind are not supported. Do not ask for help in ⁠support channels. If you cannot figure it out using those instructions, don't do it

(but if you rlly need help i'll help you lol)

**Comment by TheRealFame** [comment]
Well veskcord actually doesn't run discord in its normal electron browser 😅, But it is exactly based on vencord. Allows everything including custom rpcs, Just not the one I commonly use, that picks up a wide range of things.

**Comment by nyakowint** [comment]
Veskcord? do you mean vesktop?

**Comment by TheRealFame** [comment]
I- I keep forgetting the name of the software.. But yep! Vesktop, Even then, Vesktop also can't detect obs.. Which i sadly wish wasn't the case- So streamer mode never gets enabled

**Comment by nyakowint** [comment]
Oh okay. Back to the original question though unfortunately not as it breaks at least a few of the [plugin rules](https://github.com/Vendicated/Vencord/blob/main/CONTRIBUTING.md#plugin-rules) for PRing to main...
